development:
  auth0_domain: dev-wdp8onks0gi7ikbm.us.auth0.com
  auth0_client_id: HvRvw3QYt94u6dgFllQEnVkeKhYJEIdF
  auth0_client_secret: ktMtUbLKRsY8XZbH4DoFRowky5QVYVa8Yyg9rYil6e-I5S4WsN34KHwtIy4B7f6Y
